// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HiU1gV0sfwPs0wYByVBeH8BnB9_hqDw',
    appId: '1:640398608610:web:cbc5300d3ba684fda776bb',
    messagingSenderId: '640398608610',
    projectId: 'tbc-app-aea0c',
    authDomain: 'tbc-app-aea0c.firebaseapp.com',
    storageBucket: 'tbc-app-aea0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_oIA8Y6Yn1s0bPe5d391xGpZYoHXgzY',
    appId: '1:640398608610:android:51272cf69f1622dba776bb',
    messagingSenderId: '640398608610',
    projectId: 'tbc-app-aea0c',
    storageBucket: 'tbc-app-aea0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4kkCG8Ki0ELS-T0dWMbs7H2jG-1sU0Y',
    appId: '1:640398608610:ios:e03f3eec872550bda776bb',
    messagingSenderId: '640398608610',
    projectId: 'tbc-app-aea0c',
    storageBucket: 'tbc-app-aea0c.firebasestorage.app',
    iosBundleId: 'com.example.tbcApplication',
  );
}
